### ISSUE TITLE
Coin Balance in nebliod only shows whole number (rounds down)

### ISSUE THREAD

**Issue by go140point6** [NeblioTeam/neblio#311] opened 2020-12-23 18:39 UTC
Running 2020-12-21---v3.1.0-25bd742---nebliod---RPi-raspbian-stretch.tar.gz on Raspbian OS Buster (latest) on Pi4.  Issuing the 'getinfo' command shows, for example, a 500.29374523 wallet balance as just 500.00000000.  When switching the same exact wallet.dat to the ARM QT binary, the full 500.29374523 balance is shown as expected.

Switching back to v3.0.1 wallet daemon with same wallet.dat shows the correct full balance with 'getinfo'.

**Comment by TheQuantumPhysicist** [comment] 2020-12-27 12:18
I'm unable to reproduce this. Could it be that you hit a stake and got more coins by coincidence?

**Comment by go140point6** [comment] 2020-12-27 22:35
Double-checked and I am experiencing this with the 3.1.0 daemon (the ARM version for the Pi, don't know if this is happening on the Ubuntu Linux build).  Attached a couple screen grabs.  The neblio-3.0.1-balance.jpg was running first showing my current balance.  Flipped over to 3.1.0 with the same wallet.dat and I see what's in neblio-3.1.0-balance.jpg.

![neblio-3 0 1-balance](https://user-images.githubusercontent.com/50885069/103180987-89b73180-4850-11eb-8290-ab10a5c75114.jpg)
![neblio-3 1 0-balance](https://user-images.githubusercontent.com/50885069/103180986-891e9b00-4850-11eb-91d2-16da0c04b369.jpg)

**Comment by NeblioTeam** [comment] 2020-12-30 16:27
Fixed in v3.1.1

**Closed by NeblioTeam** 2020-12-30 16:27 UTC
