### ISSUE TITLE
Background of navigation bar buttons gets incrementally darker

### ISSUE THREAD

**Issue by pavelhadzhiev** [NeblioTeam/neblio#184] opened 2019-01-26 16:45 UTC
When you click on a tab in the navigation bar, the background goes incrementally darker until black every time your mouse enters or leaves the area of the button, clicks on it, or you swap windows.

![screen1](https://user-images.githubusercontent.com/15670670/51790258-469f4000-219b-11e9-8ff9-dfc82dd873cc.png)

Furthermore, the __NTP1 summary__ and __Send tokens__ buttons have a slightly different behaviour, specifically on swapping windows. The bottom half suffers the same issue, while the upper half resets darkness, resulting in half of the button being black, while the other half is normal.

![screen2](https://user-images.githubusercontent.com/15670670/51790261-48690380-219b-11e9-9156-e8aa6885c8a1.png)

Reproduced on neblio-Qt 2.0 for MacOS.

**Comment by NeblioTeam** [comment] 2021-05-15 15:14
This was likely a Qt bug, meaning we were waiting on Qt for a fix. I'm now unable to reproduce this on a mac with v3.2.0. Closing for now, if this is still an issue we can reopen.

**Closed by NeblioTeam** 2021-05-15 15:14 UTC
